### ISSUE TITLE
polyserve failed on cygwin, win7

### ISSUE THREAD

**Issue by renfeng** [googlecodelabs/codelab-components#7]
frren@FRREN-CN ~/git/codelab-components
$ polyserve
C:\Users\frren\AppData\Roaming\npm\node_modules\polyserve\bin\polyserve:14
const resolve = require('resolve');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by ebidel** [comment]
Please file this against polyserve.

**Comment by renfeng** [comment]
Didn't thought of there would be a polyserve project... Here it goes, https://github.com/PolymerLabs/polyserve/issues/42

(Nice number, 42 :)
